[package]
name = "iranti_ledger"
version = "1.0.0"
edition = "2024.beta"

[dependencies]
# Dependencies on Sui, MoveStdlib, etc., are automatically added by Sui CLI

[addresses]
iranti_ledger = "0x0"
